{
 "title": "mahfudl26",
 "description": "project submission Belajar Sistem Machine Learning",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Http Requests",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Request Latency p95 (Last 5 Minutes)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Total request per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(http_requests_throughput_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "python_gc_collections_total{generation=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 26 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Objek GC Terkumpul",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{generation=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime Flask Exporter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jumlah Total Koleksi GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 42 },
   "targets": [
    {
     "expr": "sum(python_gc_collections_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Bebas Sistem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 50 },
   "targets": [
    { "expr": "100 - system_ram_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Request Count - Per Endpoint",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 58 },
   "targets": [
    { "expr": "system_ram_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}